package com.notionds.dataSupplier.exceptions;

/**
 * copied from https://en.wikipedia.org/wiki/SQLSTATE
 * oracle: https://docs.oracle.com/cd/B14117_01/appdev.101/a58231/appd.htm
 *
 * Note that SQL class '46' has two different texts
 *
 */
public enum ConnectionState {
    SqlState0("00000","S","000","(no subclass)", SqlClass.Success),
    SqlState1("01000", "W", "000", "(no subclass)", SqlClass.Warning),
    SqlState2("01001", "W", "001", "cursor operation conflict", SqlClass.Warning),
    SqlState3("01002", "W", "002", "disconnect error", SqlClass.Warning),
    SqlState4("01003", "W", "003", "null value eliminated in set function", SqlClass.Warning),
    SqlState5("01004", "W", "004", "string data, right truncation", SqlClass.Warning),
    SqlState6("01005", "W", "005", "insufficient item descriptor areas", SqlClass.Warning),
    SqlState7("01006", "W", "006", "privilege not revoked", SqlClass.Warning),
    SqlState8("01007", "W", "007", "privilege not granted", SqlClass.Warning),
    SqlState9("01009", "W", "009", "search condition too long for information schema", SqlClass.Warning),
    SqlState10("0100A", "W", "00A", "query expression too long for information schema", SqlClass.Warning),
    SqlState11("0100B", "W", "00B", "default value too long for information schema", SqlClass.Warning),
    SqlState12("0100C", "W", "00C", "result sets returned", SqlClass.Warning),
    SqlState13("0100D", "W", "00D", "additional result sets returned", SqlClass.Warning),
    SqlState14("0100E", "W", "00E", "attempt to return too many result sets", SqlClass.Warning),
    SqlState15("0100F", "W", "00F", "statement too long for information schema", SqlClass.Warning),
    SqlState16("01010", "W", "010", "column cannot be mapped", "SQL/XML", SqlClass.Warning),
    SqlState17("01011", "W", "011", "SQL-Java path too long for information schema", "SQL/JRT", SqlClass.Warning),
    SqlState18("01012", "W", "012", "invalid number of conditions", SqlClass.Warning),
    SqlState19("0102F", "W", "02F", "array data, right truncation", SqlClass.Warning),
    SqlState20("02000","N", "000","(no subclass)", SqlClass.NoData),
    SqlState21("02001","N", "001","no additional result sets returned", SqlClass.NoData),
    SqlState22("07000","X", "000","(no subclass)", SqlClass.DynamicSqlError),
    SqlState23("07001","X", "001","using clause does not match dynamic parameter specifications", SqlClass.DynamicSqlError),
    SqlState24("07002","X", "002","using clause does not match target specifications", SqlClass.DynamicSqlError),
    SqlState25("07003","X", "003","cursor specification cannot be executed", SqlClass.DynamicSqlError),
    SqlState26("07004","X", "004","using clause required for dynamic parameters", SqlClass.DynamicSqlError),
    SqlState27("07005","X", "005","prepared statement not a cursor specification", SqlClass.DynamicSqlError),
    SqlState28("07006","X", "006","restricted data type attribute violation", SqlClass.DynamicSqlError),
    SqlState29("07007","X", "007","using clause required for result fields", SqlClass.DynamicSqlError),
    SqlState30("07008","X", "008","invalid descriptor count", SqlClass.DynamicSqlError),
    SqlState31("07009","X", "009","invalid descriptor index", SqlClass.DynamicSqlError),
    SqlState32("0700B","X", "00B","data type transform function violation", SqlClass.DynamicSqlError),
    SqlState33("0700C","X", "00C","undefined DATA value", SqlClass.DynamicSqlError),
    SqlState34("0700D","X", "00D","invalid DATA target", SqlClass.DynamicSqlError),
    SqlState35("0700E","X", "00E","invalid LEVEL value", SqlClass.DynamicSqlError),
    SqlState36("0700F","X", "00F","invalid DATETIME_INTERVAL_CODE", SqlClass.DynamicSqlError),
    SqlState37("08000","X", "000","(no subclass)", SqlClass.ConnectionException),
    SqlState38("08001","X", "001","SQL-client unable to establish SQL-connection", SqlClass.ConnectionException),
    SqlState39("08002","X", "002","connection name in use", SqlClass.ConnectionException),
    SqlState40("08003","X", "003","connection does not exist", SqlClass.ConnectionException),
    SqlState41("08004","X", "004","SQL-server rejected establishment of SQL-connection", SqlClass.ConnectionException),
    SqlState42("08006","X", "006","connection failure", SqlClass.ConnectionException),
    SqlState43("08007","X", "007","transaction resolution unknown", SqlClass.ConnectionException),
    SqlState44("09000","X", "000","(no subclass)", SqlClass.TriggeredActionException),
    SqlState45("0A000","X", "000","(no subclass)", SqlClass.FeatureNotSupported),
    SqlState46("0A001","X", "001","multiple server transactions", SqlClass.FeatureNotSupported),
    SqlState47("0D000","X", "000","(no subclass)", SqlClass.InvalidTargetTypeSpecification),
    SqlState48("0E000","X", "000","(no subclass)", SqlClass.InvalidSchemaNameListSpecification),
    SqlState49("0F000","X", "000","(no subclass)", SqlClass.LocatorException),
    SqlState50("0F001","X", "001","invalid specification", SqlClass.LocatorException),
    SqlState51("0K000","X", "000","(no subclass)","SQL/PSM", SqlClass.ResignalWhenHandlerNotActive),
    SqlState52("0L000","X", "000","(no subclass)", SqlClass.InvalidGrantor),
    SqlState53("0M000","X", "000","(no subclass)", SqlClass.InvalidSQLInvokedProcedureReference),
    SqlState54("0N000","X", "000","(no subclass)","SQL/XML", SqlClass.SQL_XMLMappingError),
    SqlState55("0N001","X", "001","unmappable XML name","SQL/XML", SqlClass.SQL_XMLMappingError),
    SqlState56("0N002","X", "002","invalid XML character","SQL/XML", SqlClass.SQL_XMLMappingError),
    SqlState57("0P000","X", "000","(no subclass)", SqlClass.InvalidRoleSpecification),
    SqlState58("0S000","X", "000","(no subclass)", SqlClass.InvalidTransformGroupNameSpecification),
    SqlState59("0T000","X", "000","(no subclass)", SqlClass.TargetTableDisagreesWithCursorSpecification),
    SqlState60("0U000","X", "000","(no subclass)", SqlClass.AttemptToAssignToNonUpdatableColumn),
    SqlState61("0V000","X", "000","(no subclass)", SqlClass.AttemptToAssignToOrderingColumn),
    SqlState62("0W000","X", "000","(no subclass)", SqlClass.ProhibitedStatementEncounteredDuringTriggerExecution),
    SqlState63("0W001","X", "001","modify table modified by data change delta table", SqlClass.ProhibitedStatementEncounteredDuringTriggerExecution),
    SqlState64("0X000","X", "000","(no subclass)","SQL/MED", SqlClass.InvalidForeignServerSpecification),
    SqlState65("0Y000","X", "000","(no subclass)","SQL/MED", SqlClass.PassThroughSpecificCondition),
    SqlState66("0Y001","X", "001","invalid cursor option","SQL/MED", SqlClass.PassThroughSpecificCondition),
    SqlState67("0Y002","X", "002","invalid cursor allocation","SQL/MED", SqlClass.PassThroughSpecificCondition),
    SqlState68("0Z000","X", "000","(no subclass)", SqlClass.DiagnosticsException),
    SqlState69("0Z001","X", "001","maximum number of stacked diagnostics areas exceeded", SqlClass.DiagnosticsException),
    SqlState70("0Z002","X", "002","stacked diagnostics accessed without active handler","SQL/PSM", SqlClass.DiagnosticsException),
    SqlState71("10000","X", "000","(no subclass)","SQL/XML", SqlClass.XQueryError),
    SqlState72("20000","X", "000","(no subclass)","SQL/PSM", SqlClass.CaseNotFoundForCaseStatement),
    SqlState73("21000","X", "000","(no subclass)", SqlClass.CardinalityViolation),
    SqlState74("22000","X", "000","(no subclass)", SqlClass.DataException),
    SqlState75("22001","X", "001","string data, right truncation", SqlClass.DataException),
    SqlState76("22002","X", "002","null value, no indicator parameter", SqlClass.DataException),
    SqlState77("22003","X", "003","numeric value out of range", SqlClass.DataException),
    SqlState78("22004","X", "004","null value not allowed", SqlClass.DataException),
    SqlState79("22005","X", "005","error in assignment", SqlClass.DataException),
    SqlState80("22006","X", "006","invalid interval format", SqlClass.DataException),
    SqlState81("22007","X", "007","invalid datetime format", SqlClass.DataException),
    SqlState82("22008","X", "008","datetime field overflow", SqlClass.DataException),
    SqlState83("22009","X", "009","invalid time zone displacement value", SqlClass.DataException),
    SqlState84("2200B","X", "00B","escape character conflict", SqlClass.DataException),
    SqlState85("2200C","X", "00C","invalid use of escape character", SqlClass.DataException),
    SqlState86("2200D","X", "00D","invalid escape octet", SqlClass.DataException),
    SqlState87("2200E","X", "00E","null value in array target", SqlClass.DataException),
    SqlState88("2200F","X", "00F","zero-length character string", SqlClass.DataException),
    SqlState89("2200G","X", "00G","most specific type mismatch", SqlClass.DataException),
    SqlState90("2200H","X", "00H","sequence delegation limit exceeded", SqlClass.DataException),
    SqlState91("2200J","X", "00J","nonidentical notations with the same name","SQL/XML", SqlClass.DataException),
    SqlState92("2200K","X", "00K","nonidentical unparsed entities with the same name","SQL/XML", SqlClass.DataException),
    SqlState93("2200L","X", "00L","not an XML document","SQL/XML", SqlClass.DataException),
    SqlState94("2200M","X", "00M","invalid XML document","SQL/XML", SqlClass.DataException),
    SqlState95("2200N","X", "00N","invalid XML content","SQL/XML", SqlClass.DataException),
    SqlState96("2200P","X", "00P","interval value out of range", SqlClass.DataException),
    SqlState97("2200Q","X", "00Q","multiset value overflow", SqlClass.DataException),
    SqlState98("2200R","X", "00R","XML value overflow","SQL/XML", SqlClass.DataException),
    SqlState99("2200S","X", "00S","invalid comment","SQL/XML", SqlClass.DataException),
    SqlState100("2200T","X", "00T","invalid processing instruction","SQL/XML", SqlClass.DataException),
    SqlState101("2200U","X", "00U","not an XQuery document node","SQL/XML", SqlClass.DataException),
    SqlState102("2200V","X", "00V","invalid XQuery context item","SQL/XML", SqlClass.DataException),
    SqlState103("2200W","X", "00W","XQuery serialization error","SQL/XML", SqlClass.DataException),
    SqlState104("22010","X", "010","invalid indicator parameter value", SqlClass.DataException),
    SqlState105("22011","X", "011","substring error", SqlClass.DataException),
    SqlState106("22012","X", "012","division by zero", SqlClass.DataException),
    SqlState107("22013","X", "013","invalid preceding or following size in window function", SqlClass.DataException),
    SqlState108("22014","X", "014","invalid argument for NTILE function", SqlClass.DataException),
    SqlState109("22015","X", "015","interval field overflow", SqlClass.DataException),
    SqlState110("22016","X", "016","invalid argument for NTH_VALUE function", SqlClass.DataException),
    SqlState111("22017","X", "017","invalid data specified for datalink","SQL/MED", SqlClass.DataException),
    SqlState112("22018","X", "018","invalid character value for cast", SqlClass.DataException),
    SqlState113("22019","X", "019","invalid escape character", SqlClass.DataException),
    SqlState114("2201A","X", "01A","null argument passed to datalink constructor","SQL/MED", SqlClass.DataException),
    SqlState115("2201B","X", "01B","invalid regular expression", SqlClass.DataException),
    SqlState116("2201C","X", "01C","null row not permitted in table", SqlClass.DataException),
    SqlState117("2201D","X", "01D","datalink value exceeds maximum length","SQL/MED", SqlClass.DataException),
    SqlState118("2201E","X", "01E","invalid argument for natural logarithm", SqlClass.DataException),
    SqlState119("2201F","X", "01F","invalid argument for power function", SqlClass.DataException),
    SqlState120("2201G","X", "01G","invalid argument for width bucket function", SqlClass.DataException),
    SqlState121("2201H","X", "01H","invalid row version", SqlClass.DataException),
    SqlState122("2201J","X", "01J","XQuery sequence cannot be validated","SQL/XML", SqlClass.DataException),
    SqlState123("2201K","X", "01K","XQuery document node cannot be validated","SQL/XML", SqlClass.DataException),
    SqlState124("2201L","X", "01L","no XML schema found","SQL/XML", SqlClass.DataException),
    SqlState125("2201M","X", "01M","element namespace not declared","SQL/XML", SqlClass.DataException),
    SqlState126("2201N","X", "01N","global element not declared","SQL/XML", SqlClass.DataException),
    SqlState127("2201P","X", "01P","no XML element with the specified QName","SQL/XML", SqlClass.DataException),
    SqlState128("2201Q","X", "01Q","no XML element with the specified namespace","SQL/XML", SqlClass.DataException),
    SqlState129("2201R","X", "01R","validation failure","SQL/XML", SqlClass.DataException),
    SqlState130("2201S","X", "01S","invalid Query regular expression", SqlClass.DataException),
    SqlState131("2201T","X", "01T","invalid Query option flag", SqlClass.DataException),
    SqlState132("2201U","X", "01U","attempt to replace a zero-length string", SqlClass.DataException),
    SqlState133("2201V","X", "01V","invalid Query replacement string", SqlClass.DataException),
    SqlState134("2201W","X", "01W","invalid row count in fetch first clause", SqlClass.DataException),
    SqlState135("2201X","X", "01X","invalid row count in result offset clause", SqlClass.DataException),
    SqlState136("22021","X", "021","character not in repertoire", SqlClass.DataException),
    SqlState137("22022","X", "022","indicator overflow", SqlClass.DataException),
    SqlState138("22023","X", "023","invalid parameter value", SqlClass.DataException),
    SqlState139("22024","X", "024","unterminated C string", SqlClass.DataException),
    SqlState140("22025","X", "025","invalid escape sequence", SqlClass.DataException),
    SqlState141("22026","X", "026","string data, length mismatch", SqlClass.DataException),
    SqlState142("22027","X", "027","trim error", SqlClass.DataException),
    SqlState143("22029","X", "029","noncharacter in UCS string", SqlClass.DataException),
    SqlState144("2202A","X", "02A","null value in field reference","SQL/PSM", SqlClass.DataException),
    SqlState145("2202D","X", "02D","null value substituted for mutator subject parameter", SqlClass.DataException),
    SqlState146("2202E","X", "02E","array element error", SqlClass.DataException),
    SqlState147("2202F","X", "02F","array data, right truncation", SqlClass.DataException),
    SqlState148("2202G","X", "02G","invalid repeat argument in a sample clause", SqlClass.DataException),
    SqlState149("2202H","X", "02H","invalid sample size", SqlClass.DataException),
    SqlState150("23000","X", "000","(no subclass)", SqlClass.IntegrityConstraintViolation),
    SqlState151("23001","X", "001","restrict violation", SqlClass.IntegrityConstraintViolation),
    SqlState152("24000","X", "000","(no subclass)", SqlClass.InvalidCursorState),
    SqlState153("25000","X", "000","(no subclass)", SqlClass.InvalidTransactionState),
    SqlState154("25001","X", "001","active SQL-transaction", SqlClass.InvalidTransactionState),
    SqlState155("25002","X", "002","branch transaction already active", SqlClass.InvalidTransactionState),
    SqlState156("25003","X", "003","inappropriate access mode for branch transaction", SqlClass.InvalidTransactionState),
    SqlState157("25004","X", "004","inappropriate isolation level for branch transaction", SqlClass.InvalidTransactionState),
    SqlState158("25005","X", "005","no active SQL-transaction for branch transaction", SqlClass.InvalidTransactionState),
    SqlState159("25006","X", "006","read-only SQL-transaction", SqlClass.InvalidTransactionState),
    SqlState160("25007","X", "007","schema and data statement mixing not supported", SqlClass.InvalidTransactionState),
    SqlState161("25008","X", "008","held cursor requires same isolation level", SqlClass.InvalidTransactionState),
    SqlState162("26000","X", "000","(no subclass)", SqlClass.InvalidSqlStatementName),
    SqlState163("27000","X", "000","(no subclass)", SqlClass.TriggeredDataChangeViolation),
    SqlState164("27001","X", "001","modify table modified by data change delta table", SqlClass.TriggeredDataChangeViolation),
    SqlState165("28000","X", "000","(no subclass)", SqlClass.InvalidAuthorizationSpecification),
    SqlState166("2B000","X", "000","(no subclass)", SqlClass.DependentPrivilegeDescriptorsStillExist),
    SqlState167("2C000","X", "000","(no subclass)", SqlClass.InvalidCharacterSetName),
    SqlState168("2D000","X", "000","(no subclass)", SqlClass.InvalidTransactionTermination),
    SqlState169("2E000","X", "000","(no subclass)", SqlClass.InvalidConnectionName),
    SqlState170("2F000","X", "000","(no subclass)", SqlClass.SqlRoutineException),
    SqlState171("2F002","X", "002","modifying SQL-data not permitted", SqlClass.SqlRoutineException),
    SqlState172("2F003","X", "003","prohibited SQL-statement attempted", SqlClass.SqlRoutineException),
    SqlState173("2F004","X", "004","reading SQL-data not permitted", SqlClass.SqlRoutineException),
    SqlState174("2F005","X", "005","function executed no return statement", SqlClass.SqlRoutineException),
    SqlState175("2H000","X", "000","(no subclass)", SqlClass.InvalidCollationName),
    SqlState176("30000","X", "000","(no subclass)", SqlClass.InvalidSqlStatementIdentifier),
    SqlState177("33000","X", "000","(no subclass)", SqlClass.InvalidSqlDescriptorName),
    SqlState178("34000","X", "000","(no subclass)", SqlClass.InvalidCursorName),
    SqlState179("35000","X", "000","(no subclass)", SqlClass.InvalidConditionNumber),
    SqlState180("36000","X", "000","(no subclass)", SqlClass.CursorSensitivityException),
    SqlState181("36001","X", "001","request rejected", SqlClass.CursorSensitivityException),
    SqlState182("36002","X", "002","request failed", SqlClass.CursorSensitivityException),
    SqlState183("38000","X", "000","(no subclass)", SqlClass.ExternalRoutineException),
    SqlState184("38001","X", "001","containing SQL not permitted", SqlClass.ExternalRoutineException),
    SqlState185("38002","X", "002","modifying SQL-data not permitted", SqlClass.ExternalRoutineException),
    SqlState186("38003","X", "003","prohibited SQL-statement attempted", SqlClass.ExternalRoutineException),
    SqlState187("38004","X", "004","reading SQL-data not permitted", SqlClass.ExternalRoutineException),
    SqlState188("39000","X", "000","(no subclass)", SqlClass.ExternalRoutineInvocationException),
    SqlState189("39004","X", "004","null value not allowed", SqlClass.ExternalRoutineInvocationException),
    SqlState190("3B000","X", "000","(no subclass)", SqlClass.SavepointException),
    SqlState191("3B001","X", "001","invalid specification", SqlClass.SavepointException),
    SqlState192("3B002","X", "002","too many", SqlClass.SavepointException),
    SqlState193("3C000","X", "000","(no subclass)", SqlClass.AmbiguousCursorName),
    SqlState194("3D000","X", "000","(no subclass)", SqlClass.InvalidCatalogName),
    SqlState195("3F000","X", "000","(no subclass)", SqlClass.InvalidSchemaName),
    SqlState196("40000","X", "000","(no subclass)", SqlClass.TransactionRollback),
    SqlState197("40001","X", "001","serialization failure", SqlClass.TransactionRollback),
    SqlState198("40002","X", "002","integrity constraint violation", SqlClass.TransactionRollback),
    SqlState199("40003","X", "003","statement completion unknown", SqlClass.TransactionRollback),
    SqlState200("40004","X", "004","triggered action exception", SqlClass.TransactionRollback),
    SqlState201("42000","X", "000","(no subclass)", SqlClass.SyntaxErrorOrAccessRuleViolation),
    SqlState202("44000","X", "000","(no subclass)", SqlClass.WithCheckOptionViolation),
    SqlState203("45000","X", "000","(no subclass)","SQL/PSM", SqlClass.UnhandledUserDefinedException),
    SqlState204("46000","X", "000","(no subclass)","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState205("46001","X", "001","invalid URL","SQL/JRT", SqlClass.JavaDDL),
    SqlState206("46002","X", "002","invalid JAR name","SQL/JRT", SqlClass.JavaDDL),
    SqlState207("46003","X", "003","invalid class deletion","SQL/JRT", SqlClass.JavaDDL),
    SqlState208("46005","X", "005","invalid replacement","SQL/JRT", SqlClass.JavaDDL),
    SqlState209("4600A","X", "00A","attempt to replace uninstalled JAR","SQL/JRT", SqlClass.JavaDDL),
    SqlState210("4600B","X", "00B","attempt to remove uninstalled JAR","SQL/JRT", SqlClass.JavaDDL),
    SqlState211("4600C","X", "00C","invalid JAR removal","SQL/JRT", SqlClass.JavaDDL),
    SqlState212("4600D","X", "00D","invalid path","SQL/JRT", SqlClass.JavaDDL),
    SqlState213("4600E","X", "00E","self-referencing path","SQL/JRT", SqlClass.JavaDDL),
    SqlState214("46102","X", "102","invalid JAR name in path","SQL/JRT", SqlClass.JavaDDL),
    SqlState215("46103","X", "103","unresolved class name","SQL/JRT", SqlClass.JavaDDL),
    SqlState216("46110","X", "110","unsupported feature","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState217("46120","X", "120","invalid class declaration","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState218("46121","X", "121","invalid column name","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState219("46122","X", "122","invalid number of columns","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState220("46130","X", "130","invalid profile state","SQL/OLB", SqlClass.OLB_SpecificError),
    SqlState221("HW000","X", "000","(no subclass)","SQL/MED", SqlClass.DataLinkException),
    SqlState222("HW001","X", "001","external file not linked","SQL/MED", SqlClass.DataLinkException),
    SqlState223("HW002","X", "002","external file already linked","SQL/MED", SqlClass.DataLinkException),
    SqlState224("HW003","X", "003","referenced file does not exist","SQL/MED", SqlClass.DataLinkException),
    SqlState225("HW004","X", "004","invalid write token","SQL/MED", SqlClass.DataLinkException),
    SqlState226("HW005","X", "005","invalid datalink construction","SQL/MED", SqlClass.DataLinkException),
    SqlState227("HW006","X", "006","invalid write permission for update","SQL/MED", SqlClass.DataLinkException),
    SqlState228("HW007","X", "007","referenced file not valid","SQL/MED", SqlClass.DataLinkException),
    SqlState229("HV000","X", "000","(no subclass)","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState230("HV001","X", "001","memory allocation error","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState231("HV002","X", "002","dynamic parameter value needed","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState232("HV004","X", "004","invalid data type","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState233("HV005","X", "005","column name not found","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState234("HV006","X", "006","invalid data type descriptors","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState235("HV007","X", "007","invalid column name","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState236("HV008","X", "008","invalid column number","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState237("HV009","X", "009","invalid use of null pointer","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState238("HV00A","X", "00A","invalid string format","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState239("HV00B","X", "00B","invalid handle","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState240("HV00C","X", "00C","invalid option index","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState241("HV00D","X", "00D","invalid option name","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState242("HV00J","X", "00J","option name not found","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState243("HV00K","X", "00K","reply handle","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState244("HV00L","X", "00L","unable to create execution","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState245("HV00M","X", "00M","unable to create reply","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState246("HV00N","X", "00N","unable to establish connection","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState247("HV00P","X", "00P","no schemas","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState248("HV00Q","X", "00Q","schema not found","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState249("HV00R","X", "00R","table not found","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState250("HV010","X", "010","function sequence error","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState251("HV014","X", "014","limit on number of handles exceeded","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState252("HV021","X", "021","inconsistent descriptor information","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState253("HV024","X", "024","invalid attribute value","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState254("HV090","X", "090","invalid string length or buffer length","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState255("HV091","X", "091","invalid descriptor field identifier","SQL/MED", SqlClass.FDW_SpecificCondition),
    SqlState256("HY000","X", "000","(no subclass)","SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState257("HY???","X", "n/a","dynamic parameter value needed" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState258("HY???","X", "n/a","invalid handle" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState259("HY001","X", "001","memory allocation error" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState260("HY003","X", "003","invalid data type in application descriptor" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState261("HY004","X", "004","invalid data type" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState262("HY007","X", "007","associated statement is not prepared" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState263("HY008","X", "008","operation canceled" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState264("HY009","X", "009","invalid use of null pointer" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState265("HY010","X", "010","function sequence error" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState266("HY011","X", "011","attribute cannot be set now" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState267("HY012","X", "012","invalid transaction operation code" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState268("HY013","X", "013","memory management error" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState269("HY014","X", "014","limit on number of handles exceeded" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState270("HY017","X", "017","invalid use of automatically-allocated descriptor handle" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState271("HY018","X", "018","server declined the cancellation request" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState272("HY019","X", "019","non-string data cannot be sent in pieces" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState273("HY020","X", "020","attempt to concatenate a null value" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState274("HY021","X", "021","inconsistent descriptor information" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState275("HY024","X", "024","invalid attribute value" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState276("HY055","X", "055","non-string data cannot be used with string routine" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState277("HY090","X", "090","invalid string length or buffer length" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState278("HY091","X", "091","invalid descriptor field identifier" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState279("HY092","X", "092","invalid attribute identifier" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState280("HY093","X", "093","invalid datalink value","SQL/MED", SqlClass.CLI_SpecificCondition),
    SqlState281("HY095","X", "095","invalid FunctionId specified" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState282("HY096","X", "096","invalid information type" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState283("HY097","X", "097","column type out of range" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState284("HY098","X", "098","scope out of range" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState285("HY099","X", "099","nullable type out of range" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState286("HY103","X", "103","invalid retrieval code" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState287("HY104","X", "104","invalid LengthPrecision value" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState288("HY105","X", "105","invalid parameter mode" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState289("HY106","X", "106","invalid fetch orientation" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState290("HY107","X", "107","row value out of range" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState291("HY108","X", "108","invalid cursor position" ,"SQL/CLI", SqlClass.CLI_SpecificCondition),
    SqlState292("HYC00","X", "C00","optional feature not implemented" ,"SQL/CLI", SqlClass.CLI_SpecificCondition);
    public enum SqlClass {
        Success("00", "successful completion", Recommendation.Nominal_Operation),
        Warning("01", "warning", Recommendation.Nominal_Operation),
        NoData("02", "no data"),
        DynamicSqlError("07", "dynamic SQL error"),
        ConnectionException("08","connection exception"),
        TriggeredActionException("09", "triggered action exception"),
        FeatureNotSupported("0A","feature not supported", Recommendation.Version_Fail),
        InvalidTargetTypeSpecification("0D","invalid target type specification"),
        InvalidSchemaNameListSpecification("0E","invalid schema name list specification"),
        LocatorException("0F","locator exception"),
        ResignalWhenHandlerNotActive("0K","resignal when handler not active"),
        InvalidGrantor("0L","invalid grantor"),
        InvalidSQLInvokedProcedureReference("0M","invalid SQL-invoked procedure reference"),
        SQL_XMLMappingError("0N","SQL/XML mapping error"),
        InvalidRoleSpecification("0P","invalid role specification"),
        InvalidTransformGroupNameSpecification("0S","invalid transform group name specification"),
        TargetTableDisagreesWithCursorSpecification("0T","target table disagrees with cursor specification"),
        AttemptToAssignToNonUpdatableColumn("0U","attempt to assign to non-updatable column"),
        AttemptToAssignToOrderingColumn("0V","attempt to assign to ordering column"),
        ProhibitedStatementEncounteredDuringTriggerExecution("0W","prohibited statement encountered during trigger execution"),
        InvalidForeignServerSpecification("0X","invalid foreign server specification"),
        PassThroughSpecificCondition("0Y","pass-through specific condition"),
        DiagnosticsException("0Z","diagnostics exception"),
        XQueryError("10","XQuery error"),
        CaseNotFoundForCaseStatement("20","case not found for case statement"),
        CardinalityViolation("21","cardinality violation"),
        DataException("22","data exception"),
        IntegrityConstraintViolation("23","integrity constraint violation"),
        InvalidCursorState("24","invalid cursor state"),
        InvalidTransactionState("25","invalid transaction state"),
        InvalidSqlStatementName("26","invalid SQL statement name"),
        TriggeredDataChangeViolation("27","triggered data change violation"),
        InvalidAuthorizationSpecification("28","invalid authorization specification"),
        DependentPrivilegeDescriptorsStillExist("2B","dependent privilege descriptors still exist"),
        InvalidCharacterSetName("2C","invalid character set name"),
        InvalidTransactionTermination("2D","invalid transaction termination"),
        InvalidConnectionName("2E","invalid connection name"),
        SqlRoutineException("2F","SQL routine exception"),
        InvalidCollationName("2H","invalid collation name"),
        InvalidSqlStatementIdentifier("30","invalid SQL statement identifier"),
        InvalidSqlDescriptorName("33","invalid SQL descriptor name"),
        InvalidCursorName("34","invalid cursor name"),
        InvalidConditionNumber("35","invalid condition number"),
        CursorSensitivityException("36","cursor sensitivity exception"),
        ExternalRoutineException("38","external routine exception"),
        ExternalRoutineInvocationException("39","external routine invocation exception"),
        SavepointException("3B","savepoint exception"),
        AmbiguousCursorName("3C","ambiguous cursor name"),
        InvalidCatalogName("3D","invalid catalog name"),
        InvalidSchemaName("3F","invalid schema name"),
        TransactionRollback("40","transaction rollback"),
        SyntaxErrorOrAccessRuleViolation("42","syntax error or access rule violation"),
        WithCheckOptionViolation("44","with check option violation"),
        UnhandledUserDefinedException("45","unhandled user-defined exception"),
        OLB_SpecificError("46","OLB-specific error"),
        JavaDDL("46","Java DDL"),
        DataLinkException("HW","datalink exception"),
        FDW_SpecificCondition("HV","FDW-specific condition"),
        CLI_SpecificCondition("HY","CLI-specific condition"),
        ;

        private final String code;
        private final String description;
        private final Recommendation recommendation;
        SqlClass(String code, String description) {
            this(code, description, Recommendation.Close_Closable);
        }
        SqlClass(String code, String description, Recommendation recommendation) {
            this.code = code;
            this.description = description;
            this.recommendation = recommendation;
        }
        public String getCode() {
            return this.code;
        }
        public final String getDescription() {
            return this.description;
        }
    }
    private final String code;
    private final String category;
    private final String subClass;
    private final String subClassText;
    private final String sqlPart;
    private final SqlClass sqlClass;

    private ConnectionState(String code, String category, String subClass, String subClassText, SqlClass sqlClass) {
        this(code, category, subClass, subClassText, "", sqlClass);
    }
    private ConnectionState(String code, String category, String subClass, String subClassText, String sqlPart, SqlClass sqlClass) {
        this.code = code;
        this.category = category;
        this.subClass = subClass;
        this.subClassText = subClassText;
        this.sqlPart = sqlPart;
        this.sqlClass = sqlClass;
    }

    public String getCode() {
        return code;
    }

    public String getCategory() {
        return category;
    }

    public SqlClass getSqlClass() {
        return sqlClass;
    }

    public String getSubClass() {
        return subClass;
    }

    public String getSubClassText() {
        return subClassText;
    }

    public String getSqlPart() {
        return sqlPart;
    }


}
